USE [master]
GO

CREATE DATABASE [Tucson_Reservations]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Tuscon_Reservations', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Tuscon_Reservations.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Tuscon_Reservations_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Tuscon_Reservations_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Tucson_Reservations].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Tucson_Reservations] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET ARITHABORT OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Tucson_Reservations] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Tucson_Reservations] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Tucson_Reservations] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Tucson_Reservations] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Tucson_Reservations] SET  MULTI_USER 
GO

ALTER DATABASE [Tucson_Reservations] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Tucson_Reservations] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Tucson_Reservations] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Tucson_Reservations] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Tucson_Reservations] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Tucson_Reservations] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Tucson_Reservations] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Tucson_Reservations] SET  READ_WRITE 
GO


